### ISSUE TITLE
Track user ip 2.0.6  need fix this problem

### ISSUE THREAD

**Issue by samac08** [ColetteContreras/v2ray-ssrpanel-plugin#22]
2.0.6  need fix this problem
@ColetteContreras 
I found that 2.0.6 does not display ip correctly, can not be identified by ssrpanel
The problem is that 2.0.6 does not upload the user port number.
Ssrpanel uses the user port instead of the user id to identify the user's online information.
No user port information causes ssrpanel to display an exception and the user is not recognized.
To fix this, you need to upload the user port at the same time.
I have manually added port information in the sql table,
After adding the port, ssrpanel shows normal. The problem is solved perfectly.

<img src="https://s2.ax1x.com/2019/03/12/AiEdF1.png" alt="AiEdF1.png" border="0">
<img src="https://s2.ax1x.com/2019/03/12/AiENw9.png" alt="AiENw9.png" border="0">

**Comment by ColetteContreras** [comment]
Thanks for your explanation. I've released a new version which will add port to the table, `ss_node_ip`. I hope that you could test it and give your feedback here. 

Thanks again!

**Comment by samac08** [comment]
> Thanks for your explanation. I've released a new version which will add port to the table, `ss_node_ip`. I hope that you could test it and give your feedback here.
> 
> Thanks again!
I tested the new version, the result is the same problem
Not uploaded port number corresponding to the user
<img src="https://s2.ax1x.com/2019/04/06/Afuva4.png" alt="Afuva4.png" border="0">

**Comment by samac08** [comment]
> Thanks for your explanation. I've released a new version which will add port to the table, `ss_node_ip`. I hope that you could test it and give your feedback here.
> 
> Thanks again!
-------------------------------------------------------------------
@ColetteContreras  

<img src="https://s2.ax1x.com/2019/04/06/Afuva4.png" alt="Afuva4.png" border="0">

I think the problem appears in lines 129 and 161 in panel.go
Should be wrong, UserPort=UserPort causes result=0
Page 129/161 UserPort int = UserPort: user.Port
Should be 161UserPort= Port, is correct (user_table is port) ???
I don't know much about programming, maybe, I may be wrong.

**Comment by dawfds** [comment]
Or not, port can not upload port number
@samac08

**Comment by samac08** [comment]
@ColetteContreras 3.0 port problem is not solved, datebase is show port 0

**Comment by ColetteContreras** [comment]
@samac08 
Sorry about the mistake I made! I was so stupid that I forgot to retrieve `port` field from users table. A new version of the plugin which is going to be up to date will be released in a week!

**Comment by ColetteContreras** [comment]
The bug has been fixed. Are you still willing to taste it?
